baseURL = "http://art-off-hamburg.de/preview/"

defaultContentLanguage = "de"

theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[languages]
  [languages.de]
    weight = 1
    title = "ART OFF Hamburg"
    languageCode = "de"
    languageName = "Deutsch"
    [[languages.de.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Home"
      url = ""
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1
    [[languages.de.menu.main]]
      identifier = "event"
      pre = ""
      post = ""
      name = "Veranstaltungen"
      url = "events/"
      title = "Programm – ART OFF Hamburg Kultursommer – Wir sind hier"
      weight = 2
    [[languages.de.menu.main]]
      identifier = "place"
      pre = ""
      post = ""
      name = "Kunstorte"
      url = "places/"
      title = ""
      weight = 3
    [[languages.de.menu.main]]
      identifier = "demands"
      pre = ""
      post = ""
      name = "Forderungen"
      url = "demands/"
      title = ""
      weight = 4
    [[languages.de.menu.main]]
      identifier = "imprint"
      pre = ""
      post = ""
      name = "Impressum"
      url = "imprint/"
      title = "langer Name für Impressum"
      weight = 5

  [languages.en]
    weight = 2
    title = "ART OFF Hamburg"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Home"
      url = "posts/"
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "event"
      pre = ""
      post = ""
      name = "Events"
      url = "events/"
      title = "Events Title"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "place"
      pre = ""
      post = ""
      name = "Places"
      url = "places/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "demands"
      pre = ""
      post = ""
      name = "Demands"
      url = "demands/"
      title = ""
      weight = 4
    [[languages.en.menu.main]]
      identifier = "imprint"
      pre = ""
      post = ""
      name = "Imprint"
      url = "imprint/"
      title = ""
      weight = 5


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
