backend:
  name: gitlab
  repo: art-off-hamburg/webpage-content
  auth_type: pkce
  app_id: b8f4f6a97c3d66829a375b9bd7fc0025e16be39166d30f7028cc18439c761765
  branch: master
  publish_mode: editorial_workflow
  deploy_preview: art-off-hamburg/blafoo
media_folder: static/img
public_folder: /img
collections:
  - name: 'new_event'
    label: 'Veranstaltung'
    folder: 'content/new_events/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'new_event/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Veröffentlichungszeitpunkt', name: 'publishDate', widget: 'datetime' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Untertitel', name: 'subtitle', widget: 'string' }
      - { label: 'Beginn der Veranstaltung', name: 'date', widget: 'datetime' }
      - { label: 'Ende der Veranstaltung', name: 'end', widget: 'datetime' }
      - { label: 'Straße + Hausnummer', name: 'street', widget: 'string' }
      - { label: 'PLZ + Ort', name: 'address', widget: 'string' }
      - { label: 'Kunstort', name: 'organizers', widget: 'list' }
      - { label: 'Künstler:innen', name: 'artists', widget: 'list' }
      - { label: 'Bild', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
