backend:
  name: git-gateway
  repo: art-off-hamburg/webpage-content
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: 'new_event'
    label: 'Veranstaltung'
    folder: 'content/new_events/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Veröffentlichungszeitpunkt', name: 'publishDate', widget: 'datetime', date_format: 'DD.MM.YYYY', time_format: 'HH:mm' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Untertitel', name: 'subtitle', widget: 'string' }
      - { label: 'Beginn der Veranstaltung', name: 'date', widget: 'datetime', date_format: 'DD.MM.YYYY', time_format: 'HH:mm' }
      - { label: 'Ende der Veranstaltung', name: 'end', widget: 'datetime', date_format: 'DD.MM.YYYY', time_format: 'HH:mm' }
      - { label: 'Straße + Hausnummer', name: 'street', widget: 'string' }
      - { label: 'PLZ + Ort', name: 'address', widget: 'string' }
      - { label: 'Kunstort', name: 'organizers', widget: 'relation', collection: 'places', search_fields: ['title'], value_field: 'title', multiple: true }
      - { label: 'Künstler:innen', name: 'artists', widget: 'list' }
      - { label: 'Bild', name: 'featuredImage', widget: 'image', allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'place'
    label: 'Kunstort'
    folder: 'content/places/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Veröffentlichungszeitpunkt', name: 'date', widget: 'datetime', date_format: 'DD.MM.YYYY', time_format: 'HH:mm' }
      - { label: 'Name des Kunstorts', name: 'title', widget: 'string' }
      - { label: 'Straße + Hausnummer', name: 'street', widget: 'string' }
      - { label: 'PLZ + Ort', name: 'city', widget: 'string' }
      - { label: 'Webseite', name: 'contactURL', widget: 'string' }
      - { label: 'Namens-Kachel', name: 'featuredImage', widget: 'image', allow_multiple: false }
      - { label: 'Bilder', name: 'images', widget: 'image', allow_multiple: true }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown' }
