name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: w018c78b.kasserver.com
          username: w018c78b
          password: ${{ secrets.ftp_password }}
          server-dir: ./art-off-hamburg.de/
#          dry-run: true
